---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  # pre_tasks:
  # - name: "wait 600 seconds for target connection to become reachable/usable."
  # Your code here

  # - name: "install python for Ansible."
  # Your code here

  roles:
    - configure-server
    - configure-prometheus-node-exporter

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**
    TYPEORM_HOST: udapeople-prod.cgobnho8mpje.ap-southeast-2.rds.amazonaws.com
    TYPEORM_PORT: 5532
    TYPEORM_USERNAME: udapeople
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: udapeople-prod
